name: ExternalCommand
version: 1.0
main: com.example.myplugin.MyPlugin
api-version: 1.20
commands:
  mpc:
    description: toggles the state of the music 
    usage: /mpc
  mpc_add:
    description: queries youtube, downloads the audio and puts it in mpd's queue
    usage: /mpc_add "<song>"
